const products = [
    {
      id: '1',
      name: 'Studio Headphones',
      slug: 'studio-headphones',
      price: 99.99,
      image: 'https://picsum.photos/seed/headphones/400/300',
      description: 'High-quality over-ear headphones ideal for music production and studio monitoring.',
      category: 'accessories',
    },
    {
      id: '2',
      name: 'Podcast Microphone',
      slug: 'podcast-microphone',
      price: 149.99,
      image: 'https://picsum.photos/seed/microphone/400/300',
      description: 'Professional-grade mic for crystal-clear podcast recordings.',
      category: 'accessories',
    },
    {
      id: '3',
      name: 'Tetemeko Branded T-Shirt',
      slug: 'tetemeko-tshirt',
      price: 25.0,
      image: 'https://picsum.photos/seed/tshirt/400/300',
      description: 'Cotton T-shirt with the official Tetemeko Media logo.',
      category: 'apparel',
    },
    {
      id: '4',
      name: 'Wireless Earbuds',
      slug: 'wireless-earbuds',
      price: 59.99,
      image: 'https://picsum.photos/seed/earbuds/400/300',
      description: 'Sleek wireless earbuds with long battery life and deep bass.',
      category: 'accessories',
    },
    {
      id: '5',
      name: 'Audio Mixer',
      slug: 'audio-mixer',
      price: 199.99,
      image: 'https://picsum.photos/seed/mixer/400/300',
      description: 'Compact 6-channel audio mixer for professional sound control.',
      category: 'electronics',
    },
    {
      id: '6',
      name: 'Live Stream Camera',
      slug: 'stream-camera',
      price: 249.99,
      image: 'https://picsum.photos/seed/camera/400/300',
      description: 'High-resolution streaming camera with wide-angle lens.',
      category: 'electronics',
    },
    {
      id: '7',
      name: 'Podcast Desk Stand',
      slug: 'podcast-stand',
      price: 29.99,
      image: 'https://picsum.photos/seed/stand/400/300',
      description: 'Adjustable mic stand ideal for desk setups.',
      category: 'accessories',
    },
    {
      id: '8',
      name: 'Soundproof Foam Panels',
      slug: 'foam-panels',
      price: 34.99,
      image: 'https://picsum.photos/seed/soundproof/400/300',
      description: 'Acoustic foam panels for reducing echo and improving audio quality. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laborum consequatur id, blanditiis ullam dolor placeat, voluptatibus nulla modi rem a non sunt? Cupiditate, doloremque odit assumenda dolorem, incidunt saepe quibusdam facilis dolore qui vero delectus voluptatem. Facere tenetur saepe repellendus suscipit obcaecati quis veniam, corrupti vel ipsum tempore deleniti fugit.',
      category: 'electronics',
    },
    {
      id: '9',
      name: 'Recording Light Sign',
      slug: 'recording-light',
      price: 19.99,
      image: 'https://picsum.photos/seed/recording/400/300',
      description: '"On Air" LED sign for your studio or workspace. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laborum consequatur id, blanditiis ullam dolor placeat, voluptatibus nulla modi rem a non sunt? Cupiditate, doloremque odit assumenda dolorem, incidunt saepe quibusdam facilis dolore qui vero delectus voluptatem. Facere tenetur saepe repellendus suscipit obcaecati quis veniam, corrupti vel ipsum tempore deleniti fugit.',
      category: 'accessories',
    },
    {
      id: '10',
      name: 'USB Audio Interface',
      slug: 'audio-interface',
      price: 129.99,
      image: 'https://picsum.photos/seed/interface/400/300',
      description: 'Connect your mic and instruments to your computer with high-fidelity audio. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laborum consequatur id, blanditiis ullam dolor placeat, voluptatibus nulla modi rem a non sunt? Cupiditate, doloremque odit assumenda dolorem, incidunt saepe quibusdam facilis dolore qui vero delectus voluptatem. Facere tenetur saepe repellendus suscipit obcaecati quis veniam, corrupti vel ipsum tempore deleniti fugit.',
      category: 'electronics',
    },
    {
      id: '11',
      name: 'Broadcasting Boom Arm',
      slug: 'boom-arm',
      price: 39.99,
      image: 'https://picsum.photos/seed/boomarm/400/300',
      description: 'Flexible boom arm for microphones — perfect for podcasts and voiceovers.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laborum consequatur id, blanditiis ullam dolor placeat, voluptatibus nulla modi rem a non sunt? Cupiditate, doloremque odit assumenda dolorem, incidunt saepe quibusdam facilis dolore qui vero delectus voluptatem. Facere tenetur saepe repellendus suscipit obcaecati quis veniam, corrupti vel ipsum tempore deleniti fugit.',
      category: 'accessories',
    },
    {
      id: '12',
      name: 'Editing Keyboard',
      slug: 'editing-keyboard',
      price: 89.99,
      image: 'https://picsum.photos/seed/keyboard/400/300',
      description: 'Specialized keyboard for audio and video editing workflows.',
      category: 'electronics',
    },
  ];
  
  export default products;
  